### Crear usuario
POST http://localhost:8080/usuarios 
Content-Type: application/json

{
    "name":"Luis",
    "email": "luis@gmail.com",
    "prioridad": 2
}
### Actualizar usuario (usuar id)
POST http://localhost:8080/usuarios 
Content-Type: application/json

{
    "id": 4,
    "name":"Juan",
    "email": "luis@gmail.com",
    "prioridad": 2
}

### Obtener todos usuarios
GET http://localhost:8080/usuarios

### Buscar usuario
GET http://localhost:8080/usuarios/search/2

### Buscar usuario por id
GET http://localhost:8080/usuarios/querry?prioridad=2

### Eliminar usuario
DELETE http://localhost:8080/usuarios/3